### ISSUE TITLE
Missing .param files

### ISSUE THREAD

**Issue by JaimeRZP** [fkoehlin/montepython_2cosmos_public#1]
Dear Fabian, 

Hope everything is alright and sorry to bother you again. 

I am struggling to find the .param files you refer to in the read "README" files within the Kids and the KV450 likelihoods directories. 
The root input directory only contains .run_*.sh files which require the path to the .param files. Same for the INPUT directory inside the KV450 likelihood directory. Also, I cannot find the INPUT directory with the Kids likelihood directory.  
Would it be possible for you to point me out to where the .param files are stored or upload them if for some reason they have gone missing? 

Thank you once again, 
Jaime.

**Comment by fkoehlin** [comment]
Hi Jaime,

Thanks for noticing this. The files were indeed pushed to the repo but remained hidden due to copied & pasted gitignore-settings, my apologies...
If you pull the latest commit, you can find all input-files (i.e. the `*.param` files and BASH scripts for invoking MultiNest or PolyChord runs) inside the `/your/path/to/montepython_2cosmos_public/input/` folder. 
Please double-check and close the issue if everything works now as expected or ping me again if not!

Cheers,

Fabian
